image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTHON_FILES: "config.py OpenTracksViewer.py classes/*.py otv/*.py"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

install_dependencies:
  stage: build
  script:
    - pip install -r requirements.txt

lint:
  stage: test
  script:
    - pip install -r requirements-linting.txt
    - flake8 ${PYTHON_FILES}
    - pylint ${PYTHON_FILES}
  
typing:
  stage: test
  script:
    - pip install -r requirements-typing.txt
    - mypy ${PYTHON_FILES}