image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate


install_dependencies:
  stage: build
  script:
    - pip install -r requirements.txt -r requirements-test.txt

lint:
  stage: test
  script:
    - flake8 
    - pylint .
  
typing:
  stage: test
  script:
    - mypy